allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  cpu-features: false
  esbuild: true
  prisma: true
  protobufjs: true
  ssh2: false
  unrs-resolver: false
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma

  - protobufjs
