"use client";
import { use, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Pause, Play } from "lucide-react";
import { Shell } from "@/components/shell";
import { api, Badge, CopyButton, ErrorBox, Refresh, useData } from "@/components/ui";

type Detail = { id: string; applicationId: string; name: string; status: string; ingestionUrl?: string; destinationUrl: string | null; endpointId: string | null; lastEventReceivedAt: string | null; lastVerifiedAt: string | null; lastVerificationFailure: string | null; lastVerificationFailureAt: string | null; canManage: boolean; provider: { displayName: string; docsUrl: string }; attempts: { id: string; status: string; httpStatusCode: number | null; createdAt: string; event: { id: string; type: string } }[] };
export default function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { data, error, reload } = useData<Detail>(`/api/sources/${id}`, true);
  const [failure, setFailure] = useState("");
  const [busy, setBusy] = useState(false);
  return <Shell><Link className="back" href={data ? `/applications/${data.applicationId}#sources` : "/dashboard"}><ArrowLeft size={14} /> Webhook Sources</Link><div className="page-head"><div><div className="eyebrow">WEBHOOK SOURCE</div><h1>{data?.name || "Loading source…"}</h1><p className="muted">{data?.provider.displayName} · {data && <Badge value={data.status} />}</p></div><Refresh onClick={reload} /></div><ErrorBox error={error || failure} />
    {data && <><div className="source-summary"><section className="panel panel-body"><h2>Connection</h2>{data.ingestionUrl && <><p className="muted">Provider ingestion URL</p><div className="secret-row"><code>{data.ingestionUrl}</code><CopyButton value={data.ingestionUrl} /></div></>}<p>Destination: <code>{data.destinationUrl || "Not set"}</code></p><p>Last verified webhook: {data.lastVerifiedAt ? new Date(data.lastVerifiedAt).toLocaleString() : "Waiting"}</p><p>Last received: {data.lastEventReceivedAt ? new Date(data.lastEventReceivedAt).toLocaleString() : "None"}</p><a href={data.provider.docsUrl} target="_blank" rel="noopener noreferrer">Provider setup documentation ↗</a>{data.canManage && data.status !== "SETUP_IN_PROGRESS" && <div className="action-row"><button className="btn secondary" disabled={busy} onClick={async () => { setBusy(true); setFailure(""); try { await api(`/api/sources/${id}`, { status: data.status === "PAUSED" ? "ACTIVE" : "PAUSED" }, "PATCH"); await reload(); } catch (e) { setFailure((e as Error).message); } finally { setBusy(false); } }}>{data.status === "PAUSED" ? <Play size={16} /> : <Pause size={16} />}{data.status === "PAUSED" ? "Resume" : "Pause"}</button></div>}</section><section className="panel panel-body"><h2>Verification</h2>{data.lastVerificationFailure ? <><Badge value="FAILED" /><p>{data.lastVerificationFailure}</p><p className="muted">{data.lastVerificationFailureAt && new Date(data.lastVerificationFailureAt).toLocaleString()}</p></> : <p className="muted">No recent signature failures.</p>}<p>Invalid requests receive a generic response. This detail is visible only in your workspace.</p></section></div><section className="panel"><div className="panel-head"><h2>Delivery attempts</h2></div>{data.attempts.length ? <div className="table-wrap"><table><thead><tr><th>Event</th><th>Status</th><th>HTTP</th><th>Time</th></tr></thead><tbody>{data.attempts.map(attempt => <tr key={attempt.id}><td><span className="mono">{attempt.event.type}</span><br /><small className="muted">{attempt.event.id}</small></td><td><Badge value={attempt.status} /></td><td>{attempt.httpStatusCode || "—"}</td><td>{new Date(attempt.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="empty">No delivery attempts yet.</div>}</section></>}
  </Shell>;
}
