"use client";
import Link from "next/link";
import { ArrowRight, ArrowDown, ArrowUpRight, Check, Github, ShieldCheck, RotateCcw, Fingerprint, Activity, Users, Terminal, Webhook, Layers3 } from "lucide-react";
import { Brand } from "./shell";
import { PreferencesMenu, T } from "./preferences";
import { CodeBlock } from "./ui";
const features = [
  { icon: RotateCcw, title: "Retries with a plan", body: "Durable delivery work and configurable retry policies keep transient failures from becoming lost work." },
  { icon: ShieldCheck, title: "Protection at the edge", body: "Circuit breakers give failing receivers room to recover. Pause, resume and throttle each destination." },
  { icon: Fingerprint, title: "One event. A stable identity.", body: "Idempotency keys prevent duplicate submissions. Signed event IDs help receivers safely deduplicate deliveries." },
  { icon: Webhook, title: "Standard Webhooks", body: "Verify deliveries with an open signature standard. Rotate signing keys with a seven-day transition window." },
  { icon: Activity, title: "Every attempt, explained", body: "Inspect delivery logs, latency and response details. AI diagnosis helps investigate patterns without changing your receiver." },
  { icon: Users, title: "Built for your team", body: "Separate applications into workspaces, assign roles and give customers a scoped endpoint portal." },
];
function DeliveryFlow() {
  return <div className="delivery-flow"><div className="flow-caption"><span className="dot" /><T text="A route for the unexpected" /></div><svg viewBox="0 0 960 270" role="img" aria-labelledby="flow-title flow-description"><title id="flow-title">Hooka Relay delivery flow</title><desc id="flow-description">Your application sends an event to a durable queue. The worker delivers it to your endpoint. A failed attempt follows a delay queue before retrying.</desc><defs><marker id="flow-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6" fill="none" stroke="currentColor" strokeWidth="1.5" /></marker></defs><g className="flow-lines" fill="none" strokeWidth="2" markerEnd="url(#flow-arrow)"><path d="M206 100H315" /><path d="M506 100H615" /><path d="M806 100H912" /><path className="retry-path" d="M716 146V220H406V146" /></g><g className="flow-boxes"><rect x="16" y="55" width="190" height="90" rx="15"/><rect x="316" y="55" width="190" height="90" rx="15"/><rect x="616" y="55" width="190" height="90" rx="15"/></g><g className="flow-labels" textAnchor="middle"><text x="111" y="95"><T text="Your application" /></text><text x="411" y="95"><T text="Durable queue" /></text><text x="711" y="95"><T text="Your endpoint" /></text></g><g className="flow-sublabels" textAnchor="middle"><text x="111" y="119">POST /events</text><text x="411" y="119">Postgres → RabbitMQ</text><text x="711" y="119">HTTPS · HMAC-SHA256</text><text x="555" y="251"><T text="Failure → delay → retry" /></text></g><circle className="flow-packet packet-one" cx="258" cy="100" r="5"/><circle className="flow-packet packet-two" cx="558" cy="100" r="5"/><circle className="flow-packet packet-three" cx="860" cy="100" r="5"/><g className="flow-success"><circle cx="929" cy="100" r="17"/><path d="m922 100 5 5 9-11" fill="none" strokeWidth="2"/></g></svg><div className="mobile-flow"><div className="flow-step"><Terminal size={20} /><strong><T text="Your application" /></strong><code>POST /events</code></div><ArrowDown aria-hidden="true" /><div className="flow-step"><Layers3 size={20}/><strong><T text="Durable queue" /></strong><code>Postgres → RabbitMQ</code></div><ArrowDown aria-hidden="true" /><div className="flow-step"><Webhook size={20}/><strong><T text="Your endpoint" /></strong><code>HTTPS · HMAC-SHA256</code></div><p><RotateCcw size={14}/><T text="Failure → delay → retry" /></p></div><p className="muted"><T text="Accepted first. Delivered asynchronously. Every attempt leaves a trail." /></p></div>;
}
export function Landing() {
  return <div className="landing"><header className="landing-header"><Brand /><nav aria-label="Main navigation"><Link href="/docs"><T text="Documentation" /></Link><Link href="/status"><T text="Status" /></Link><a href="https://github.com/wauul/hooka-relay" aria-label="Hooka Relay on GitHub"><Github size={19} /></a></nav><div className="landing-header-actions"><PreferencesMenu /><Link className="btn secondary" href="/login"><T text="Sign in" /><ArrowRight size={15}/></Link></div></header>
    <main id="main-content">
      <section className="landing-hero"><div><div className="eyebrow"><span className="dot" /> WEBHOOK DELIVERY, UNDER CONTROL</div><h1><T text="Send once." /><br/><span><T text="Deliver with confidence." /></span></h1><p className="landing-lead"><T text="Your app creates the event. Hooka Relay handles the delivery trail: signed webhooks, retries, recovery and the tools to see what happened." /></p><div className="action-row"><Link className="btn" href="/signup"><T text="Start delivering" /><ArrowRight size={17}/></Link><Link className="btn secondary" href="/docs"><Terminal size={17}/><T text="Read the quickstart" /></Link></div><p className="landing-note"><Check size={14}/><T text="Free to start. Open source. No credit card." /></p></div><div className="hero-terminal"><div className="terminal-label"><span/><span/><span/><small>send-event.sh</small></div><CodeBlock>{String.raw`curl -X POST "$RELAY_URL/api/v1/events" \
  -H "Authorization: Bearer $API_KEY" \
  -H "Content-Type: application/json" \
  -d '{
    "type": "order.shipped",
    "idempotencyKey": "order-1042-shipped",
    "payload": { "orderId": "ord_1042" }
  }'`}</CodeBlock><div className="terminal-result"><span className="badge"><Check size={12}/>202 ACCEPTED</span><span><T text="Stored. Queued. Ready to deliver." /></span></div></div></section>
      <section className="landing-flow-section" aria-label="Delivery architecture"><DeliveryFlow /></section>
      <section className="landing-section" id="features"><div className="landing-section-heading"><div className="eyebrow">RELIABILITY IS IN THE DETAILS</div><h2><T text="The delivery layer your product deserves." /></h2><p className="muted"><T text="Build your product. Keep control of the difficult delivery cases." /></p></div><div className="feature-grid">{features.map(({icon: Icon,title,body})=><article className="feature-card" key={title}><span className="feature-icon"><Icon size={23}/></span><h3><T text={title}/></h3><p><T text={body}/></p></article>)}</div></section>
      <section className="landing-section why-section"><div className="landing-section-heading"><div className="eyebrow">WHY HOOKA RELAY</div><h2><T text="Fewer blind spots. More useful answers." /></h2><p className="muted"><T text="A delivery failure should be something you can investigate, understand and recover from." /></p></div><div className="why-list"><article><span>01</span><div><h3><T text="See the evidence" /></h3><p><T text="Follow an event from acceptance to its delivery attempts. Inspect the actual status, timing and captured response." /></p></div></article><article><span>02</span><div><h3><T text="Recover deliberately" /></h3><p><T text="Browse missed events and replay failed deliveries when your receiver is ready. No silent backfills or hidden changes." /></p></div></article><article><span>03</span><div><h3><T text="Keep the protocol open" /></h3><p><T text="Standard signatures, documented behavior and open-source SDKs make your integration portable and reviewable." /></p></div></article></div></section>
      <section className="landing-section tools-section"><div><div className="eyebrow">MEET YOUR WORKFLOW</div><h2><T text="Your language. Your terminal." /></h2><p className="muted"><T text="Send events with a typed SDK, verify signatures with the reference standard, or follow deliveries from the command line." /></p></div><div className="tool-links"><a href="https://www.npmjs.com/package/hooka-relay-node"><Layers3 size={20}/><span>Node.js SDK<small>hooka-relay-node</small></span><ArrowUpRight size={17}/></a><a href="https://pypi.org/project/hooka-relay-python/"><Layers3 size={20}/><span>Python SDK<small>hooka-relay-python</small></span><ArrowUpRight size={17}/></a><a href="https://www.npmjs.com/package/hooka-relay-cli"><Terminal size={20}/><span>hooka CLI<small>send · tail · replay</small></span><ArrowUpRight size={17}/></a></div></section>
      <section className="landing-cta"><Webhook size={30}/><h2><T text="Give your next event a reliable route." /></h2><p><T text="Create a workspace, connect a destination, and send your first test event." /></p><Link className="btn" href="/signup"><T text="Create an account" /><ArrowRight size={17}/></Link><small><T text="At-least-once delivery. Bounded retries. No ordering guarantee. Clear documentation." /></small></section>
    </main><footer className="landing-footer"><Brand /><p><T text="The last mile, handled." /></p><nav aria-label="Footer"><Link href="/docs"><T text="Documentation" /></Link><Link href="/status"><T text="Status" /></Link><a href="https://github.com/wauul/hooka-relay">GitHub</a><Link href="/privacy"><T text="Privacy" /></Link><Link href="/terms"><T text="Terms of Use" /></Link></nav></footer>
  </div>;
}
