import { T } from "@/components/preferences";
import { PreferencesMenu } from "@/components/preferences";
import Link from "next/link";
import { Brand } from "@/components/shell";
export const metadata = { title: "Terms of Use — Hooka Relay" };
export default function TermsPage() {
  return <main id="main-content" className="legal-page"><header className="public-header"><Brand /><PreferencesMenu /></header><h1><T text={"Terms of Use"} /></h1><p className="muted">Effective 25 September 2026</p><p>These terms describe use of the hosted Hooka Relay service, maintained by Wael Fezari. Hooka Relay helps you send, monitor and retry outbound webhooks. Contact <a className="auth-link" href="mailto:waelfezari@gmail.com">waelfezari@gmail.com</a> with questions about these terms.</p>
    <h2>Your account and workspace</h2><p>Use accurate account information and keep your credentials, API keys, signing secrets and private portal links secure. Only invite people or register destinations you are authorized to use. Workspace owners control their members and application data; make sure you have permission before acting for an organization.</p>
    <h2>Acceptable use</h2><p>Do not use Hooka Relay to send unlawful content, spam or malicious traffic; access systems without permission; probe private networks; bypass security or rate limits; or interfere with other users. Test receivers only with their owner’s permission. We may restrict abusive activity or suspend access when needed to protect the service or comply with law.</p>
    <h2>Your content and data</h2><p>You retain your rights to the data you submit. You authorize processing and transmission of that data as needed to provide the delivery, history, recovery and support features you use. You are responsible for the content and destinations of your webhooks and for having the necessary permissions to send that data. Our <Link className="auth-link" href="/privacy">Privacy & data use page</Link> describes storage, providers and AI processing.</p>
    <h2>Delivery behavior and availability</h2><p>Service limits and any paid pilot terms must be agreed separately. No public price or uptime or delivery-time service-level agreement is offered here. Delivery is asynchronous and at least once: duplicates and out-of-order deliveries can occur, and attempts may ultimately fail. Verify signatures, make receivers idempotent, monitor failures and keep your own records of important events. Paused endpoints do not automatically receive a backfill when resumed. Completed event payloads and delivery history are normally removed after 30 days, which also ends replay and idempotency lookup for those events; unfinished work is retained until complete.</p>
    <h2>AI assistance</h2><p>Support answers and failure diagnoses can be incomplete or incorrect. Review suggestions before relying on them. Do not submit passwords, API keys or other secrets in chat or receiver error responses. The support assistant cannot manage your workspace or make changes for you.</p>
    <h2>Ending use and changes</h2><p>You can stop using the service at any time. Workspace owners can delete workspace data through the dashboard; account or data requests can be sent to the contact address above. Deletion actions are permanent. Features and limits may change; material changes to these terms will be published here with an updated effective date and brought to users’ attention through the service where appropriate.</p>
    <h2>Service limitations</h2><p>The service is provided on an as-available basis. We do not promise uninterrupted operation, suitability for a particular purpose or error-free results. Nothing in these terms excludes rights or protections that applicable law does not allow to be excluded.</p>
    <nav className="legal-links" aria-label="Legal navigation"><Link href="/"><T text={"Home"} /></Link><Link href="/privacy"><T text={"Privacy"} /></Link><Link href="/docs"><T text={"Documentation"} /></Link></nav>
  </main>;
}
