"use client";
import { use, useState } from "react";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Search, Webhook } from "lucide-react";
import { Shell } from "@/components/shell";
import { api, CopyButton, ErrorBox, useData } from "@/components/ui";

type Provider = { name: string; displayName: string; icon: string; docsUrl: string; setupInstructions: string[]; testEventSupport: boolean };
type SourceDetail = { lastVerifiedAt: string | null; attempts: { status: string; event: { id: string } }[] };
function TestStep({ sourceId, provider, onDone }: { sourceId: string; provider: Provider; onDone: () => Promise<void> }) {
  const { data, error } = useData<SourceDetail>(`/api/sources/${sourceId}`, true);
  const [simulationId, setSimulationId] = useState("");
  const [busy, setBusy] = useState(false);
  const [failure, setFailure] = useState("");
  const verified = !!data?.lastVerifiedAt;
  const simulation = !!simulationId && !!data?.attempts.some(attempt => attempt.event.id === simulationId && attempt.status === "SUCCESS");
  return <div className="wizard-card"><h2>Test the connection</h2><ErrorBox error={error || failure} />
    {provider.testEventSupport ? <><p>Finish configuring the webhook in {provider.displayName} now, then send a test event. This page checks for a correctly signed event every few seconds.</p><div className="wizard-wait">{verified ? <><CheckCircle2 size={18} /> Verified event received</> : <>Waiting for a verified {provider.displayName} event…</>}</div></> : <><p>Run a simulated event through Hooka Relay&apos;s real delivery engine. This tests your destination, but it does not verify a real {provider.displayName} signature.</p><button className="btn secondary" disabled={busy} onClick={async () => { setBusy(true); setFailure(""); try { const result = await api<{eventId:string}>(`/api/sources/${sourceId}/simulate`, {}); setSimulationId(result.eventId); } catch (e) { setFailure((e as Error).message); } finally { setBusy(false); } }}>Simulate a test event</button>{simulationId && <div className="wizard-wait">{simulation ? <><CheckCircle2 size={18} /> Destination accepted the event</> : "Waiting for a successful delivery attempt…"}</div>}</>}
    <div className="wizard-actions"><button className="btn" disabled={busy || !(verified || simulation)} onClick={async () => { setBusy(true); setFailure(""); try { await onDone(); } catch (e) { setFailure((e as Error).message); setBusy(false); } }}>Activate source <ArrowRight size={16} /></button></div>
  </div>;
}
export default function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id: applicationId } = use(params);
  const { data: catalog, error: catalogError } = useData<Provider[]>("/api/webhook-providers");
  const [step, setStep] = useState(0);
  const [search, setSearch] = useState("");
  const [provider, setProvider] = useState<Provider>();
  const [name, setName] = useState("");
  const [sourceId, setSourceId] = useState("");
  const [ingestionUrl, setIngestionUrl] = useState("");
  const [secret, setSecret] = useState("");
  const [destinationUrl, setDestinationUrl] = useState("");
  const [signatureHeader, setSignatureHeader] = useState("");
  const [algorithm, setAlgorithm] = useState("sha256");
  const [encoding, setEncoding] = useState("hex");
  const [signaturePrefix, setSignaturePrefix] = useState("");
  const [signedPayload, setSignedPayload] = useState("body");
  const [timestampHeader, setTimestampHeader] = useState("");
  const [timestampFormat, setTimestampFormat] = useState("{timestamp}.{body}");
  const [busy, setBusy] = useState(false);
  const [failure, setFailure] = useState("");
  const titles = ["Choose provider", "Name source", "Ingestion URL", "Signing secret", "Destination", "Test", "Done"];
  async function proceed(work: () => Promise<void>) { setBusy(true); setFailure(""); try { await work(); setStep(current => current + 1); } catch (e) { setFailure((e as Error).message); } finally { setBusy(false); } }
  return <Shell><Link className="back" href={`/applications/${applicationId}#sources`}><ArrowLeft size={14} /> Webhook Sources</Link><div className="page-head"><div><div className="eyebrow">SETUP WIZARD</div><h1>Connect a webhook provider</h1><p className="muted">Receive signed events and forward them to your own backend with reliable delivery.</p></div></div>
    <ol className="wizard-progress" aria-label="Setup progress">{titles.map((title, i) => <li key={title} aria-current={step === i ? "step" : undefined} className={i < step ? "complete" : ""}><span>{i < step ? "✓" : i + 1}</span>{title}</li>)}</ol><ErrorBox error={catalogError || failure} />
    {step === 0 && <div className="wizard-card"><h2>Choose a provider</h2><p>These providers have implemented signature verification. For another provider, choose Custom / Manual.</p><label className="wizard-search"><Search size={17} /><input aria-label="Search providers" placeholder="Search providers" value={search} onChange={e => setSearch(e.target.value)} /></label><div className="provider-grid">{catalog?.filter(item => item.displayName.toLowerCase().includes(search.toLowerCase())).map(item => <button type="button" className={`provider-choice ${item.name === "CUSTOM" ? "manual" : ""}`} key={item.name} onClick={() => { setProvider(item); setStep(1); }}><span className="provider-mark">{item.icon}</span><strong>{item.displayName}</strong><small>Signature verification</small></button>)}</div></div>}
    {step === 1 && provider && <form className="wizard-card" onSubmit={event => { event.preventDefault(); void proceed(async () => { const created = await api<{id:string;ingestionUrl:string}>(`/api/applications/${applicationId}/sources`, { provider: provider.name, name }); setSourceId(created.id); setIngestionUrl(created.ingestionUrl); }); }}><h2>Name this source</h2><p>Use a label you will recognize in event logs, such as “{provider.displayName} — production.”</p><label>Source name<input value={name} onChange={event => setName(event.target.value)} maxLength={100} required /></label><div className="wizard-actions"><button type="button" className="btn quiet" onClick={() => setStep(0)}>Back</button><button className="btn" disabled={busy}>Generate ingestion URL <ArrowRight size={16} /></button></div></form>}
    {step === 2 && provider && <div className="wizard-card"><h2>Get your {provider.displayName} ingestion URL</h2><p>This URL is unique to this source. Keep it private. You can finish the provider setup during the test step, after saving the signing secret and destination. Slack requires that order to verify its Request URL.</p><div className="secret-row"><code>{ingestionUrl}</code><CopyButton value={ingestionUrl} /></div><ol className="wizard-instructions">{provider.setupInstructions.map(instruction => <li key={instruction}>{instruction}</li>)}</ol><a href={provider.docsUrl} target="_blank" rel="noopener noreferrer">Open {provider.displayName} setup docs ↗</a><div className="wizard-actions"><button className="btn" onClick={() => setStep(3)}>Continue to signing secret <ArrowRight size={16} /></button></div></div>}
    {step === 3 && provider && <form className="wizard-card" onSubmit={event => { event.preventDefault(); void proceed(async () => { await api(`/api/sources/${sourceId}`, { providerSecret: secret, ...(provider.name === "CUSTOM" ? { manualConfig: { signatureHeader, algorithm, encoding, signaturePrefix, signedPayload, ...(signedPayload === "timestamp-body" ? { timestampHeader, timestampFormat } : {}) } } : {}) }, "PATCH"); setSecret(""); }); }}><h2>Enter the provider signing secret</h2><p>Copy it from {provider.displayName}. Hooka Relay encrypts it and never shows it again.</p><label>Signing secret<input type="password" value={secret} onChange={event => setSecret(event.target.value)} autoComplete="off" required /></label>{provider.name === "CUSTOM" && <div className="wizard-manual"><h3>Manual signature format</h3><label>Signature header<input placeholder="X-Webhook-Signature" value={signatureHeader} onChange={e => setSignatureHeader(e.target.value)} required /></label><label>Algorithm<select value={algorithm} onChange={e => setAlgorithm(e.target.value)}><option value="sha256">HMAC-SHA256</option><option value="sha1">HMAC-SHA1</option></select></label><label>Encoding<select value={encoding} onChange={e => setEncoding(e.target.value)}><option value="hex">Hex</option><option value="base64">Base64</option></select></label><label>Signature prefix, if any<input placeholder="sha256=" value={signaturePrefix} onChange={e => setSignaturePrefix(e.target.value)} /></label><label>Signed payload<select value={signedPayload} onChange={e => setSignedPayload(e.target.value)}><option value="body">Raw body only</option><option value="timestamp-body">Timestamp and raw body</option></select></label>{signedPayload === "timestamp-body" && <><label>Timestamp header<input value={timestampHeader} onChange={e => setTimestampHeader(e.target.value)} required /></label><label>Exact format<input value={timestampFormat} onChange={e => setTimestampFormat(e.target.value)} required /></label><p className="muted">Use {'{timestamp}'} and {'{body}'} placeholders; for example, {'{timestamp}.{body}'}.</p></>}</div>}<div className="wizard-actions"><button type="button" className="btn quiet" onClick={() => setStep(2)}>Back</button><button className="btn" disabled={busy}>Save secret <ArrowRight size={16} /></button></div></form>}
    {step === 4 && <form className="wizard-card" onSubmit={event => { event.preventDefault(); void proceed(async () => { await api(`/api/sources/${sourceId}`, { destinationUrl }, "PATCH"); }); }}><h2>Where should verified events go?</h2><p>Enter your backend&apos;s public HTTPS URL. Delivery uses the same retries, circuit breaker, and event log as other Hooka Relay endpoints.</p><label>Destination URL<input type="url" placeholder="https://api.example.com/webhooks" value={destinationUrl} onChange={e => setDestinationUrl(e.target.value)} required /></label><div className="wizard-actions"><button type="button" className="btn quiet" onClick={() => setStep(3)}>Back</button><button className="btn" disabled={busy}>Save destination <ArrowRight size={16} /></button></div></form>}
    {step === 5 && provider && <TestStep sourceId={sourceId} provider={provider} onDone={async () => { await api(`/api/sources/${sourceId}`, { status: "ACTIVE" }, "PATCH"); setStep(6); }} />}
    {step === 6 && <div className="wizard-card wizard-done"><CheckCircle2 size={36} /><h2>Source is active</h2><p>Verified webhooks now flow through Hooka Relay to your destination.</p><dl><dt>Ingestion URL</dt><dd><code>{ingestionUrl}</code></dd><dt>Destination</dt><dd>{destinationUrl}</dd></dl><div className="wizard-actions"><Link className="btn" href={`/sources/${sourceId}`}>View live event log</Link><Link className="btn secondary" href={`/applications/${applicationId}#sources`}>Back to sources</Link></div></div>}
  </Shell>;
}
